'use client';

import React, { useState } from 'react';
import {
  ShieldCheck,
  Download,
  CheckCircle2,
  FileCode,
  FileText,
  Layers,
  Cpu,
  Hash,
  Ruler,
} from 'lucide-react';

export default function EvidenceVaultPage() {
  const [unit, setUnit] = useState<'km2' | 'ha' | 'acres'>('km2');

  const rawKm2 = 4.5896;
  const formatArea = (km2: number) => {
    if (unit === 'ha') return (km2 * 100).toFixed(1) + ' ha';
    if (unit === 'acres') return (km2 * 247.105).toFixed(1) + ' acres';
    return km2.toFixed(4) + ' km²';
  };

  return (
    <main className="h-full w-full overflow-y-auto px-6 py-8 max-w-6xl mx-auto flex flex-col gap-8">
      {/* 1. Vault Header */}
      <section className="flex flex-col md:flex-row items-start md:items-end justify-between gap-4 border-b border-white/5 pb-6">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs font-medium mb-3">
            <ShieldCheck className="w-3.5 h-3.5" />
            <span>Zero-Hallucination Evidence Vault</span>
          </div>
          <h1 className="text-3xl font-semibold tracking-tight text-white">
            Mathematical Verification & Provenance
          </h1>
          <p className="text-neutral-400 text-sm mt-1 max-w-2xl">
            Every textual claim generated by the system is linked to raw raster pixels, deep Siamese feature maps, and verifiable physical area integrals.
          </p>
        </div>

        {/* Unit Segmented Control */}
        <div className="flex items-center p-1 rounded-full bg-neutral-900 border border-white/10 text-xs">
          <button
            onClick={() => setUnit('km2')}
            className={`px-3 py-1 rounded-full font-medium transition ${
              unit === 'km2' ? 'bg-white/15 text-white' : 'text-neutral-400 hover:text-white'
            }`}
          >
            Square Km
          </button>
          <button
            onClick={() => setUnit('ha')}
            className={`px-3 py-1 rounded-full font-medium transition ${
              unit === 'ha' ? 'bg-white/15 text-white' : 'text-neutral-400 hover:text-white'
            }`}
          >
            Hectares
          </button>
          <button
            onClick={() => setUnit('acres')}
            className={`px-3 py-1 rounded-full font-medium transition ${
              unit === 'acres' ? 'bg-white/15 text-white' : 'text-neutral-400 hover:text-white'
            }`}
          >
            Acres
          </button>
        </div>
      </section>

      {/* 2. Primary Verified Claims */}
      <section className="flex flex-col gap-4">
        <h2 className="text-sm font-semibold text-neutral-400 uppercase tracking-wider font-mono">
          Cryptographically Verified Claims
        </h2>

        <div className="space-y-3">
          <div className="p-5 rounded-3xl bg-neutral-900/40 backdrop-blur-xl border border-white/5 flex items-start gap-4">
            <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0 mt-1" />
            <div className="flex-1">
              <div className="flex items-center gap-2 mb-1">
                <span className="text-xs font-mono font-semibold text-emerald-400">CLAIM_244D28</span>
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-300 border border-emerald-500/20">
                  VERIFIED 100%
                </span>
              </div>
              <p className="text-sm text-white leading-relaxed">
                Water-covered area decreased from 26.2144 km² to 24.6784 km² (a net shift of -5.86%) between 2020 and 2026, coupled with 46,080 pixels of riparian vegetation loss along the river corridor.
              </p>
              <div className="mt-3 flex items-center gap-4 text-xs text-neutral-400 font-mono">
                <span>Model: TinyCD Siamese U-Net</span>
                <span>•</span>
                <span>Confidence: 94.2%</span>
                <span>•</span>
                <span>Delta Area: -1.5360 km²</span>
              </div>
            </div>
          </div>

          <div className="p-5 rounded-3xl bg-neutral-900/40 backdrop-blur-xl border border-white/5 flex items-start gap-4">
            <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0 mt-1" />
            <div className="flex-1">
              <div className="flex items-center gap-2 mb-1">
                <span className="text-xs font-mono font-semibold text-emerald-400">CLAIM_4B1FEC</span>
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-300 border border-emerald-500/20">
                  VERIFIED 100%
                </span>
              </div>
              <p className="text-sm text-white leading-relaxed">
                Multi-sensor fusion successfully delineated 20.3062 km² of total water extent, including 2.644 km² penetrated beneath 30.04% cloud cover using Sentinel-1 C-band specular backscatter.
              </p>
              <div className="mt-3 flex items-center gap-4 text-xs text-neutral-400 font-mono">
                <span>Model: SEN12MS Cross-Modal Dual-Stream</span>
                <span>•</span>
                <span>Confidence: 96.0%</span>
                <span>•</span>
                <span>Radar Gain: +2.644 km²</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 3. Physical Metrics Breakdown */}
      <section className="grid grid-cols-1 md:grid-cols-3 gap-5">
        <div className="p-6 rounded-3xl bg-neutral-900/30 border border-white/5 flex flex-col justify-between">
          <div className="flex items-center justify-between text-neutral-400 text-xs">
            <span>Changed Terrain Extent</span>
            <Ruler className="w-4 h-4 text-cyan-400" />
          </div>
          <div className="my-4">
            <div className="text-3xl font-semibold text-white font-mono">{formatArea(rawKm2)}</div>
            <span className="text-xs text-neutral-400 mt-1 block">45,896 pixels at 10m GSD</span>
          </div>
          <span className="text-[10px] text-neutral-500 font-mono">EPSG:32644 (UTM Zone 44N)</span>
        </div>

        <div className="p-6 rounded-3xl bg-neutral-900/30 border border-white/5 flex flex-col justify-between">
          <div className="flex items-center justify-between text-neutral-400 text-xs">
            <span>Specialist Neural Architecture</span>
            <Cpu className="w-4 h-4 text-purple-400" />
          </div>
          <div className="my-4">
            <div className="text-lg font-semibold text-white">TinyCD Siamese MAMB</div>
            <span className="text-xs text-neutral-400 mt-1 block">310,000 Parameters (0.31M)</span>
          </div>
          <span className="text-[10px] text-emerald-400 font-mono">Sub-second CPU Inference</span>
        </div>

        <div className="p-6 rounded-3xl bg-neutral-900/30 border border-white/5 flex flex-col justify-between">
          <div className="flex items-center justify-between text-neutral-400 text-xs">
            <span>Authoritative RAG Grounds</span>
            <Layers className="w-4 h-4 text-amber-400" />
          </div>
          <div className="my-4">
            <div className="text-lg font-semibold text-white">ESA & ISRO Standards</div>
            <span className="text-xs text-neutral-400 mt-1 block">Sentinel-1 GRD / Cartosat Spec</span>
          </div>
          <span className="text-[10px] text-neutral-500 font-mono">10 Document Chunks Indexed</span>
        </div>
      </section>

      {/* 4. Export Actions Strip */}
      <section className="p-6 rounded-3xl bg-neutral-900/20 border border-white/5 flex flex-col sm:flex-row items-center justify-between gap-4">
        <div>
          <h3 className="text-sm font-semibold text-white">Export Audit Dossiers</h3>
          <p className="text-xs text-neutral-400 mt-0.5">
            Download verified mathematical summaries and GIS polygon layers for official review.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <a
            href="http://localhost:5000/api/investigations/demo_nepal_hydrology/report?format=geojson"
            target="_blank"
            rel="noreferrer"
            className="flex items-center gap-2 px-4 py-2 rounded-full bg-white/10 hover:bg-white/15 text-neutral-200 text-xs font-medium border border-white/10 transition"
          >
            <FileCode className="w-4 h-4 text-emerald-400" />
            <span>GeoJSON Vectors</span>
          </a>
          <a
            href="http://localhost:5000/api/investigations/demo_nepal_hydrology/report?format=markdown"
            target="_blank"
            rel="noreferrer"
            className="flex items-center gap-2 px-4 py-2 rounded-full bg-white text-neutral-950 text-xs font-medium hover:bg-neutral-200 transition shadow"
          >
            <FileText className="w-4 h-4 text-cyan-600" />
            <span>Markdown Dossier</span>
          </a>
        </div>
      </section>
    </main>
  );
}
